language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: linhs-super-cool-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: WNEMhQNXvG+TG4AJEWPyQMNO4X+80Z0KHjxYGII5Jy1CMxvFiczK02DacS8WVYK6y8xo4mhHZ0lrCVifLbYRwR4G+/GDhPAr+CxnDyrOfmKVk8hcflFZYI2lzNKCH+4GhoDXLuVQZU8UaKLioNLbXYGivGHUV32Tu6J++q0UdO7BopSGI3WpN22UPBcxN13n3iDjrn2sXLdqnTx5vGeppI1FEHhhdktXid/P/gAB0aDhUNO/LTrSRkOsGkojOllxjqy+TvWXMCNp2FVI5AXDw+/+7w1tGJ3xeSnfCI5kSk64Eh55QOpBUcUMqG0j4cS8BM3pQo7e9ca8H0CF5sfy2jXaniGhi65NZ+tzCsU95WE6d6plp9ifZeJRnRIABmUTdGr1K75oKJCzC4+lLCk1E4e1G5CcQXd+SC0PmVir34GuDfqYPQNx1FYNNH3VXFOCnsdbZVyjxrLUvezMvtDoQcrlVbEWfALfhYEnpn1rwkoA4p40K31LJRZNboEHE5AsFY463ib06fbiXZ7fLXQJwuOjPQB5m1z93IbDOguYxpemxE3Q/HFJQs8WiMEKdB+lLiT0A3dRsWSKYLQ3tjWuR3g+Mme9kN0uKltJ0T/V4dnMq78O8XrkoKlY9Zyl/cVByuYRAnis/IEBylHWd9AlaO7pHhqwKomdwFHfLxL7F+E=
